### ISSUE TITLE
Nest a Checklist block within a Table cell

### ISSUE THREAD

**Issue by genericbar** [anyproto/anytype-ts#343]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

As of version 0.35.4, it is not possible to nest a _Checklist_ block inside a _Table_ cell as these blocks need to be separate on different lines, similar to the example below:

| Header 1 | Header 2 |
|--------|--------|
| Cell 1 | Cell 2 |

- [ ] Checklist 1
- [ ] Checklist 2

### Suggested solution

I'd like to be able to create a _Checklist_ inside any given _Table_ cell in order to be able to do multiple tracking on a per row basis. Example created in MS Word below:

![Screenshot 2023-11-05 105603](https://github.com/anyproto/anytype-ts/assets/23086343/5ae97264-1d5f-49d5-a7be-bad49d26e517)
